- name: Deploy Zabbix 7.0
  hosts: zabbix
  become: yes
  vars:
    zabbix_db_config:
      host: "192.168.3.2"
      name: "zabbix"
      user: "root"
      password: "alex12345"
    php_timezone: "America/Bogota"

  tasks:
    - name: Add Zabbix repository
      apt:
        deb: https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_7.0-1+ubuntu24.04_all.deb

    - name: Refresh package cache
      apt:
        update_cache: yes

    - name: Ensure locales are installed
      apt:
        name: locales
        state: present

    - name: Verify en_US.UTF-8 locale is available
      command: locale -a
      register: locale_output

    - name: Debug locales list
      debug:
        msg: "{{ locale_output.stdout_lines }}"

    - name: Generate en_US.UTF-8 locale if not available
      command: locale-gen en_US.UTF-8
      when: "'en_US.UTF-8' not in locale_output.stdout_lines"

    - name: Apply locale changes using localectl
      command: localectl set-locale LANG=en_US.UTF-8

    - name: Ensure locale settings are persistent
      lineinfile:
        path: /etc/default/locale
        regexp: '^LANG='
        line: 'LANG=en_US.UTF-8'

    - name: Install Zabbix packages
      apt:
        name:
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-agent
        state: present

    - name: Create Zabbix server configuration file dynamically
      copy:
        dest: /etc/zabbix/zabbix_server.conf
        content: |
          # Zabbix server configuration file
          LogFile=/var/log/zabbix/zabbix_server.log
          PidFile=/var/run/zabbix/zabbix_server.pid
          DBHost={{ zabbix_db_config.host }}
          DBName={{ zabbix_db_config.name }}
          DBUser={{ zabbix_db_config.user }}
          DBPassword={{ zabbix_db_config.password }}
          StartPollers=5
          Timeout=4
        owner: zabbix
        group: zabbix
        mode: '0640'
      notify: restart zabbix-server

    - name: Update PHP timezone
      lineinfile:
        path: /etc/zabbix/apache.conf
        regexp: '^.*php_value date.timezone.*'
        line: "        php_value date.timezone {{ php_timezone }}"
      notify: restart apache2

    - name: Handle initial DB schema
      block:
        - name: Retrieve SQL dump
          slurp:
            src: /usr/share/zabbix-sql-scripts/mysql/server.sql.gz
          register: zabbix_sql_dump
          delegate_to: 192.168.3.3

        - name: Upload SQL dump to database host
          copy:
            content: "{{ zabbix_sql_dump['content'] | b64decode }}"
            dest: /tmp/server.sql.gz
          delegate_to: "{{ zabbix_db_config.host }}"

        - name: Decompress SQL dump
          shell: gunzip -f /tmp/server.sql.gz
          delegate_to: "{{ zabbix_db_config.host }}"

        - name: Import database schema
          mysql_db:
            name: "{{ zabbix_db_config.name }}"
            state: import
            target: /tmp/server.sql
            login_user: "{{ zabbix_db_config.user }}"
            login_password: "{{ zabbix_db_config.password }}"
            login_host: "{{ zabbix_db_config.host }}"
          delegate_to: "{{ zabbix_db_config.host }}"
          run_once: true

    - name: Ensure Zabbix and Apache services are running
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - zabbix-server
        - zabbix-agent
        - apache2

  handlers:
    - name: restart zabbix-server
      service:
        name: zabbix-server
        state: restarted

    - name: restart apache2
      service:
        name: apache2
        state: restarted
